//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintOrder
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long id { get; set; }
        public long orderID { get; set; }
        public long productID { get; set; }
        public int number { get; set; }
        public double price { get; set; }
    }
}
